---
title: "Master's Presentation"
author: "Matt Partridge"
date: "October 4, 2017"
output: ioslides_presentation
---

<!-- Outline
- Introduction (5 minutes)
    - The Dashboard
    - Purpose
    - Intended Uses
    - How to Launch
- Methods (23 minutes)
    - Features of this Dashboard
    - Using the Dashboard (Features and Examples)
    - Statistical Formulas
    - R Functions
- Discussion (8 minutes)
    - Limitations
    - Future Improvements
- Questions (10 minutes)
- Closed Door (45 minutes)

~30-40 minutes for 1-3 (4:00 - 4:40)
~10-20 minutes for 4 (4:40 - 5:00)
~30-50 minutes for 5 (5:00 - 5:30)

-->

## Outline {.smaller}
- Introduction
    - The Dashboard
    - Purpose
    - Intended Uses
    - How to Launch
- Methods
    - Features of this Dashboard
    - Using the Dashboard (Features and Examples)
    - Statistical Formulas
    - R Functions
- Discussion
    - Limitations
    - Future Improvements

## The Dashboard
- Interactive Shiny Dashboard developped with R in RStudio
- Calculates sample size and power (and margin of error) for various study scenarios
- Outputs results in real-time

## Purpose
- Sample size and power calculations are a vital aspect of scientific studies
- Most calculators require submitting results for each calculation or tweak
- The Piface application (Russel Lenth) is no longer being supported

## Intended Uses
- Clinical trials
- Verrification of effectiveness
- Education
- etc.

## How to Launch {.smaller}
- <https://mfpartridge.shinyapps.io/shiny_dashboard_for_sample_sizes_and_power/>
- Download the ui.R and server.R from GitHub at <https://github.com/mattpartridge/ShinySampleSizes> and run in RStudio

## Features of this Dashboard
- Interactive text boxes and sliders
    - Allows the user to see variable dependencies in real time
- Dynamic user interface
    - The page updates the inputs that can be manipulated depending on the scenario and what is being calculated
- Conditional inputs
    - Specifically for the Time to Event scenario, certain inputs are only displayed when certain conditions of a different variable are met
- Reactive values
    - The server reacts to a slider (text box) being changed and updates the corresponding text box (slider) to make it appear like the two inputs are connected

## Using the Dashboard {.smaller}
<https://mfpartridge.shinyapps.io/shiny_dashboard_for_sample_sizes_and_power/>

<!-- Outline for in dashboard work
## Setting up the calculation
- Select the scenario from the side panel
- Specify what is being calculated at the top of the page

## The Calculations
- Numeric inputs can be entered in the text box or by using the slider
    - Slider bounds will update as the value moves
- Categorical variables can be selected with drop-down inputs
- The calculation, outlined in green, updates after inputs are changed in real-time

## Examples
- Background info
- Enterinputs with explanation
- Examine output
- Show variable interdependencies by changing various inputs and examining outputs
    - A couple of examples from OM, OP, TM, TP,
    - At least one example from TTE
-->

## Statistical Formulas
- One and Two Sample Mean(s): Student's $t$-Test
- One and Two Sample Proportion(s): $Z$-Test
- Time to Event: Equality of Hazards Test

## R Functions
- One Sample Mean: `pwr.t.test`
- One Sample Proportion: `pwr.p.test`
- Two Sample Means: `pwr.t2n.test`
- Two Sample Proportions: `pwr.2p2n.test`
- Time to Event
    - Sample Size: `nSurvival`
    - Power: `nSurvival` and `nEvents`

## Limitations
- Layout
    - Inputs should be grouped by relevant categories
    - Need to see output while adjusting any input
    - Especially relevant for the Time to Event scenario
- Calculation selector
    - Calculate sample size until the sample size input is manipulated
    - Then calculate power until the power input is manipulated
    - Current attempts resulted in infinite loops
    - Selector at the top of the page is clunky

## Future Improvements
- Slider bounds
- Additional options for functions (e.g. alternative hypothesis)
- Code consolidation and streamlining
- Additional educational dialogue
- Adding documentation to the dashboard itself
